[package]
name = "scylla_orm_query_parser"
version = "0.1.0"
authors = ["Jasper Visser <jasperav@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
scylla_orm_macro = { path = "../scylla_orm_macro" }
trybuild = "1"

[dependencies]
# TODO :change to 'real' scylla driver
scylla = { git = "https://github.com/Jasperav/scylla-rust-driver", branch = "main" }
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
scylla_orm = { path = "../scylla_orm" }
proc-macro2 = "1"
uuid = "0.8"
regex = "1"
scylla_orm_table_to_struct = { path = "../scylla_orm_table_to_struct" }